server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8787/eureka}
      
spring:
   application:
      name: Gateway 
   cloud:
      gateway:
         routes:
         - id: thirdService
           uri: lb://thirdService
           predicates:
           - Path=/thirdService/**
         - id: authenticationService
           uri: lb://authenticationService
           predicates:
           - Path=/auth/**
         - id: songsSonglistsService
           uri: lb://songsSonglistsService
           predicates:
           - Path=/songs/**