spring:
   main:
      allow-bean-definition-overriding: true
   application:
      name: authenticationService
   datasource:
      url: jdbc:mysql://localhost/AuthDB?useSSL=false
      username: root
      password: Pauloss2208
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
            show_sql: true
            format_sql: false
#            naming:
#              physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#            naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
              
server:
   port: 8082
eureka:
   client:
      serviceUrl:
         defaultZone: ${EUREKA_URI:http://localhost:8787/eureka}