spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: songsSonglistsService
  datasource:
    url: jdbc:mysql://bkdynbmvz80fhyg4xinz.cppwdtivsn16.eu-central-1.rds.amazonaws.com/bkdynbmvz80fhyg4xinz?useSSL=false
    username: root
    password: Pauloss2208
  jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
            show_sql: true
            format_sql: false
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8787/eureka}