spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: songsSonglistsService
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8787/eureka}